apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  selector:
    matchLabels:
      app: search-service
  replicas: 1
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: mericalpp/search_service:latest  # Update the tag as needed
        ports:
        - containerPort: 8080
