version: "3.4"
services:

  animal-service:
    image: mericalpp/animal_service:lts
    ports:
      - "7001:7001"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RescueUs_Animals;User Id=SA;Password=Password123;MultipleActiveResultSets=True;TrustServerCertificate=True;
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Information
      - ASPNETCORE_URLS=http://+:7001
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - app_network

  search-service:
    image: mericalpp/search_service:lts  
    ports:
      - "8080:8080" 
    environment:
      CORS_ORIGIN: "http://localhost:3000"
      SPRING_DATA_MONGODB_DATABASE: "SearchDb"
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb_container:27017/SearchDb"
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "guest"
      SPRING_RABBITMQ_PASSWORD: "guest"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_AMQP: "DEBUG"
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

    depends_on:
      - mongodb_container
      - rabbitmq
    networks:
      - app_network

  react-app:
    image: mericalpp/ui_animal_app:lts  
    ports:
      - "3000:3000"  
    depends_on:
      - animal-service
      - search-service
    networks:
      - app_network

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_USER: "SA"
      MSSQL_SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - app_network

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - './mongodb_data_container:/data/db'
    restart: always
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app_network

networks:
  app_network:
    driver: bridge