version: "3.4"
services:

  # react:
  #   build:
  #     context: ./react
  #     dockerfile: Dockerfile-react
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - animal-service
  #     - search-service

  # animal-service:
  #   build:
  #     context: ./animal-service
  #     dockerfile: Dockerfile-dotnet
  #   ports:
  #     - "5000:80"

  # search-service:
  #   build:
  #     context: ./search-service
  #     dockerfile: Dockerfile-springboot
  #   ports:
  #     - "8080:8080"

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf

  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_USER: "SA"
      MSSQL_SA_PASSWORD: "Password123"
      MSSQL_PID: "Developer"
      # docker run -e "ACCEPT_EULA=1" -e "MSSQL_SA_PASSWORD=MyPass@word" -e 
      # "MSSQL_PID=Developer" -e "MSSQL_USER=SA" -p 1433:1433 -d --name=sql mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    restart: always

    # volumes:
    #   - './drive:/var/opt/mssql'
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - './mongodb_data_container:/data/db'
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

