# Dockerfile
FROM mcr.microsoft.com/azure-sql-edge

# Environment variables
ENV ACCEPT_EULA=1 \
    MSSQL_USER=SA \
    MSSQL_SA_PASSWORD=Password123 \
    MSSQL_PID=Developer

# Expose the SQL Server port
EXPOSE 1433

 